apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-spot-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spot-app
  template:
    metadata:
      labels:
        app: spot-app
    spec:
      nodeSelector:
        # This requests that the Pod runs on a node backed by a Spot VM
        cloud.google.com/gke-spot: "true"
      containers:
      - name: my-container
        image: nginx:latest
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
